http:
  port: "8081"
  
rabbitmq:
  host: "localhost"
  port: "5672"
  virtualHost: "dev"
  username: "guest"
  password: "guest"
  addexchange: "address-exchange"



retry:
  threshold: "1"
  ttl: "5"
  